name: GetFront Testing Pipeline 🧪

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    matrix:
      node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} 🔂
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile --silent

      - name: Run unit tests ⚛️
        run: yarn test
