name: GetFront RN SDK Testing Pipeline 🧪

on: [push]

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile --silent

      - name: Run lint checks  🕵️‍♂️
        run: yarn lint

  types-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile --silent

      - name: Run types checks  🕵️‍♂️
        run: yarn types-check

  unit-tests:
    runs-on: ${{ matrix.os }}
    needs:
      - lint-checks
      - types-check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} 🔂
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile --silent

      - name: Run unit tests ⚛️
        run: yarn test

  check-build:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile --silent

      - name: Build package 📦
        run: yarn build

      - name: Check build 🕵️‍♂️
        run: yarn check-build
